import { overview, inventory, headingNew, shellNew, utilityNew } from './workspace.js';
import { esc, icon, badge, time, number } from './utils.js';
import { network } from './network.js';
import { metrics, lineChart, bars } from './charts.js';
import { scenarios, roles } from '../data/mock-events.js';
import { techniques, techniqueUrl } from '../data/mitre-data.js';
import { analysisStages } from './ai-analysis.js';
import { llmPanel } from './llm-panel.js';

export const nav = [
  ['command', 'Overview', 'grid'], ['network', 'Network', 'network'], ['traffic', 'Event stream', 'activity'], ['alerts', 'Alert queue', 'alert'], ['investigations', 'Investigations', 'search'], ['response', 'Response log', 'shield'], ['devices', 'Devices & connection', 'devices'], ['lab', 'Scenarios', 'flask'], ['analytics', 'Analytics', 'chart'], ['mitre', 'MITRE ATT&CK', 'layers'], ['architecture', 'Windows logs', 'network'], ['about', 'About this project', 'info']
];
const subtitles = { command: 'Events, sources, and decisions from your local lab.', network: 'See which lab devices exchanged activity.', traffic: 'Inspect incoming Windows events and controlled lab records.', alerts: 'Review detections with their supporting event records.', investigations: 'Inspect the event sequence and decide what happens next.', mitre: 'View the techniques modeled by this lab.', response: 'Review analyst decisions and simulated containment.', lab: 'Generate controlled activity and follow its events.', devices: 'Connect a device or inspect observed lab sources.', analytics: 'Review the activity and results collected in this session.', architecture: 'See how Windows records become analyst reviewed decisions.', about: 'SOC Analyst · Final-year engineering project' };
export const heading = headingNew;
export const shell = shellNew;
export const utility = utilityNew;
export function metricStrip(s) {
  const m = metrics(s), items = [
    ['TOTAL EVENTS', number(s.totalEvents), 'Across the current environment', ''],
    ['ACTIVE ALERTS', String(m.active.length).padStart(2, '0'), 'Requiring analyst attention', ''],
    ['CRITICAL', String(m.active.filter(a => a.severity === 'critical').length).padStart(2, '0'), 'Immediate response', 'red'],
    ['HIGH', String(m.active.filter(a => a.severity === 'high').length).padStart(2, '0'), 'Priority investigations', 'amber'],
    ['FALSE POSITIVES', String(m.suppressed).padStart(2, '0'), 'Filtered by local analysis', 'green'],
    ['ACTIVE DEVICES', String(s.devices.filter(d => d.status === 'Connected').length).padStart(2, '0'), `${s.devices.length} registered lab assets`, ''],
    ['AI INVESTIGATIONS', String(m.reviewed.length).padStart(2, '0'), 'Completed assessments', 'cyan-text'],
    ['AVG. ANALYSIS', `${m.analysisTime}${m.reviewed.length ? 's' : ''}`, 'Measured simulated latency', '']
  ];
  return `<div class="metrics-strip">${items.map(([label, value, foot, cls]) => `<div class="metric"><div class="metric-label">${label}</div><div class="metric-value ${cls}">${value}</div><div class="metric-foot">${foot}</div></div>`).join('')}</div>`;
}
export function pipeline(s, a) {
  const pending = a || s.alerts.find(x => !x.analysis), current = pending ? [3, 2, 4, 4, 5, 6, 7][pending.stage] : 8;
  const steps = ['Collect', 'Normalize', 'Correlate', 'Alert', 'Analyze', 'Classify', 'Explain', 'Respond'];
  return `<div class="pipeline-strip"><div class="pipeline-intro">${icon('ai')}<div><b>Intelligence pipeline</b><small>${pending && !pending.analysis ? esc(pending.state) : 'Local deterministic analysis'}</small></div></div><div class="pipeline-steps">${steps.map((step, i) => `${i ? '<span class="pipeline-arrow">›</span>' : ''}<span class="pipeline-step ${i < current || !pending ? 'complete' : i === current ? 'active' : ''}"><i class="dot"></i>${step}</span>`).join('')}</div></div>`;
}
const panelHead = (title, glyph, action = '') => `<div class="panel-header"><div class="heading">${icon(glyph)}<h2>${title}</h2></div>${action}</div>`;
const goto = (route, text) => `<a class="text-button" href="#${route}">${text} ${icon('arrow')}</a>`;
export const command = overview;
export function compactAlert(a) {
  return `<button class="alert-compact" data-alert="${a.id}"><div class="alert-compact-top">${badge(a.severity)}<span class="mono">${a.id}</span><time>${time(a.timestamp)}</time></div><div class="alert-compact-title">${esc(a.title)}${icon('chevron')}</div><div class="alert-compact-meta"><span class="mono">${esc(a.sourceIp)}</span><span>→</span><span>${esc(a.techniques.join(' · ') || 'Local rule')}</span><span class="right">${a.analysis ? `${a.analysis.confidence}% confidence` : esc(a.state)}</span></div></button>`;
}
export function empty(title, detail, glyph = 'shield') { return `<div class="empty-state">${icon(glyph)}<h3>${title}</h3><p>${detail}</p></div>`; }
export function trafficTable(events, compact = false) {
  if (!events.length) return empty('Waiting for records', 'Start Windows collection with npm run setup:windows, connect a portal device, or run a scenario.', 'activity');
  return `<div class="table-wrap ${compact ? 'traffic-preview' : ''}" id="traffic-table-wrap"><table><thead><tr><th>TIME</th><th>ORIGIN / SOURCE</th><th>RECORD</th>${compact ? '' : '<th>DESTINATION</th><th>PROTOCOL / PORT</th><th>ACCOUNT</th>'}<th>RESULT</th>${compact ? '' : '<th>RISK</th>'}<th>ACTION</th></tr></thead><tbody>${events.map(e => { const source = e.origin; const evidence = e.windowsEvent ? `Windows event ${e.windowsEvent.eventId} · ${e.windowsEvent.logName} · ${e.windowsEvent.detail}` : ''; return `<tr><td class="mono muted">${time(e.timestamp)}</td><td><b>${esc(e.sourceDevice || e.sourceIp)}</b><small class="table-secondary mono">${esc(e.sourceIp)} · ${esc(source)}</small></td><td><b>${esc(e.label)}</b><small class="table-secondary">${esc(e.id)}${evidence ? ` · ${esc(evidence)}` : ''}</small></td>${compact ? '' : `<td><b>${esc(e.destinationDevice || 'Endpoint')}</b><small class="table-secondary mono">${esc(e.destinationIp)}</small></td><td class="mono">${esc(e.protocol)}${e.port ? ` / ${e.port}` : ''}</td><td>${esc(e.user)}</td>`}<td class="mono muted">${e.status}</td>${compact ? '' : `<td>${badge(e.risk)}</td>`}<td><span class="action-text ${e.action.toLowerCase()}">${esc(e.action)}</span></td></tr>`; }).join('')}</tbody></table></div>`;
}
export function traffic(s, ui) {
  const devices = s.devices.map(d => `<option value="${d.ip}">${d.ip}</option>`).join('');
  const windowsCount=s.events.filter(e=>e.origin==='Windows Event Log').length, portalCount=s.events.filter(e=>e.origin==='Lab portal'||e.origin==='Portal simulation').length, scenarioCount=s.events.filter(e=>e.origin==='Synthetic').length;
  return `<section class="event-console"><div class="event-console-head"><div><p class="eyebrow">INCOMING EVENTS</p><h2>Event stream</h2><p>Windows Security event ID, host, account, and event details stay attached.</p></div><span class="stream-state ${ui.paused?'paused':''}"><i></i>${ui.paused?'Paused':'Stream connected'}</span></div><div class="event-source-counts"><span><i class="source-dot windows"></i>Windows logs <b>${number(windowsCount)}</b></span><span><i class="source-dot portal"></i>Portal <b>${number(portalCount)}</b></span><span><i class="source-dot simulation"></i>Scenarios <b>${number(scenarioCount)}</b></span><span class="rate-inline">${metrics(s).eps.toFixed(1)} records / sec</span></div><div class="toolbar"><div class="search-field">${icon('search')}<input id="traffic-search" placeholder="Find a hostname, Windows event ID, IP, or account" aria-label="Search traffic" value="${esc(ui.traffic.search)}"></div><select id="filter-source" aria-label="Source filter"><option value="">All sources</option>${devices}</select><select id="filter-destination" aria-label="Destination filter"><option value="">All destinations</option>${devices}</select><select id="filter-protocol" aria-label="Protocol filter"><option value="">All protocols</option><option>HTTPS</option><option>HTTP</option><option>TCP</option><option>DNS</option><option>ICMP</option><option>HOST</option></select><select id="filter-risk" aria-label="Severity filter"><option value="">All risks</option><option value="critical">Critical</option><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select><select id="filter-status" aria-label="Status filter"><option value="">All actions</option><option>Allowed</option><option>Monitoring</option><option>Blocked</option></select><button class="button small" data-action="pause-stream">${icon(ui.paused ? 'play' : 'pause')}${ui.paused ? 'Resume' : 'Pause'}</button><label class="follow-newest"><input type="checkbox" id="auto-scroll" ${ui.autoScroll ? 'checked' : ''}> Follow newest</label></div><div id="traffic-results">${trafficResults(s, ui)}</div></section><p class="fine-print spaced">Windows event IDs stay attached to each record. Pause freezes this view; collection continues.</p>`;
}
export function trafficResults(s, ui) {
  const filter = ui.traffic, source = ui.pausedEvents || s.events;
  const events = source.filter(e => Number(e.id.split('-')[1]) > ui.clearBefore && (!filter.search || [e.label, e.user, e.sourceIp, e.destinationIp, e.id, e.origin, e.sourceEventId, e.windowsEvent?.eventId, e.windowsEvent?.detail].join(' ').toLowerCase().includes(filter.search.toLowerCase())) && (!filter.source || e.sourceIp === filter.source) && (!filter.destination || e.destinationIp === filter.destination) && (!filter.protocol || e.protocol === filter.protocol) && (!filter.risk || e.risk === filter.risk) && (!filter.status || e.action === filter.status));
  return `${trafficTable(events.slice(0, 150))}<div class="table-footer"><span>${events.length} matching records · ${ui.paused ? 'VIEW PAUSED' : 'LIVE'}</span><span>Showing up to 150 most recent records</span></div>`;
}
export function alerts(s, ui) {
  const tabs = ['All', 'Critical', 'High', 'Medium', 'Low', 'Rule reviewed', 'Pending', 'False positive', 'True positive'];
  const filter = ui.alertFilter;
  const list = s.alerts.filter(a => filter === 'All' || a.severity === filter.toLowerCase() || (filter === 'Rule reviewed' && a.analysis) || (filter === 'Pending' && !a.analysis) || a.analysis?.classification === filter);
  return `${heading('alerts')}<div class="filter-tabs">${tabs.map(t => `<button class="filter-tab ${filter === t ? 'active' : ''}" data-alert-filter="${t}">${t} ${t === 'All' ? `<span class="count">${s.alerts.length}</span>` : ''}</button>`).join('')}</div><section class="panel">${panelHead('Alert investigation queue', 'alert', `<span class="muted">${list.length} matching alerts</span>`)}${list.length ? `<div class="table-wrap"><table class="alert-table"><thead><tr><th>SEVERITY</th><th>ALERT / RULE</th><th>SOURCE → TARGET</th><th>DETECTED</th><th>MITRE ATT&CK</th><th>RULE CLASSIFICATION</th><th>STATE</th></tr></thead><tbody>${list.map(a => `<tr><td>${badge(a.severity)}</td><td><button class="alert-link" data-alert="${a.id}">${a.id}</button><span class="alert-title">${esc(a.title)}</span><span class="muted">${a.eventIds.length} events · ${esc(a.initialRule)}</span></td><td class="mono">${a.sourceIp}<br><span class="muted">→ ${a.destinationIp}</span></td><td class="mono muted">${time(a.timestamp)}</td><td class="mono cyan-text">${a.techniques.join('<br>') || '—'}</td><td>${a.analysis ? badge(a.analysis.classification) + `<div class="muted">${a.analysis.confidence}% heuristic confidence</div>` : badge('Pending', 'neutral')}</td><td>${badge(a.state, a.decision === 'approve' ? 'contained' : 'neutral')}</td></tr>`).join('')}</tbody></table></div>` : empty('No matching alerts', 'Choose another filter or run a scenario from the Simulation Lab.')}</section>`;
}
export function investigations(s, ui) {
  const a = s.alerts.find(a => a.id === ui.selectedAlert) || s.alerts.find(a => a.rule === 'compromise') || s.alerts[0];
  if (!a) return `${heading('investigations')}${llmPanel(null, ui.config)}<section class="panel">${empty('Your investigation workspace is ready', 'Run a suspicious login sequence to build an evidence timeline, retrieve context, and generate an assessment.', 'ai')}<div class="panel-body">${goto('lab', 'Open Simulation Lab')}</div></section>`;
  const events = s.events.filter(e => a.eventIds.includes(e.id)).sort((a, b) => Date.parse(a.timestamp) - Date.parse(b.timestamp));
  return `${heading('investigations')}<div class="context-strip"><a href="#alerts" class="text-button">← Alert queue</a><span class="footer-separator">/</span><span>${a.id}</span><label class="right"><select id="investigation-select" aria-label="Select investigation">${s.alerts.map(x => `<option value="${x.id}" ${a.id === x.id ? 'selected' : ''}>${x.id} · ${esc(x.title)}</option>`).join('')}</select></label></div><section class="panel"><div class="investigation-header"><div><span class="eyebrow">ALERT #${a.id} · ${time(a.timestamp)}</span><h2>${esc(a.title)}</h2><p class="mono muted no-margin spaced">${esc(s.devices.find(d=>d.ip===a.sourceIp)?.hostname || a.sourceIp)} · ${a.sourceIp} → ${a.destinationIp} · ${esc(a.user)} · ${a.eventIds.length} correlated events</p></div><div class="investigation-stats">${badge(a.severity)} ${a.analysis ? badge(a.analysis.classification) : badge(a.state, 'neutral')}<div class="confidence-value">${a.analysis?.confidence || '—'}<small>%</small> <small class="muted">Rule confidence</small></div></div></div></section>${pipeline(s, a)}${llmPanel(a, ui.config)}<div class="investigation-layout"><section class="panel"><div class="panel-header"><h2>Event timeline</h2><span class="count">${events.length}</span></div><div class="timeline">${events.map(e => `<div class="timeline-item ${e.risk !== 'low' ? 'danger' : ''}"><time>${time(e.timestamp)}</time><p>${esc(e.label)}</p><small>${e.status} · ${esc(e.user)} · ${e.id}</small></div>`).join('')}</div><div class="panel-body"><p class="eyebrow">INITIAL DETECTION</p><p class="mono muted">${esc(a.initialRule)}</p><p class="eyebrow spaced">DATA PROVENANCE</p><p class="muted">${events.some(e => e.fixture) ? 'Seeded demonstration fixture' : events.some(e => e.origin === 'Portal simulation') ? 'Controlled sequence triggered by a registered device' : events.some(e => e.origin === 'Lab portal') ? 'Intentional portal interactions' : events.some(e => e.origin === 'Windows Event Log') ? 'Windows Security event received from the local collector' : 'Controlled synthetic scenario'}</p></div></section><div class="stack">${a.analysis ? analysisContent(a) : `<section class="panel"><div class="panel-body"><p class="eyebrow">INVESTIGATION IN PROGRESS</p><h3>${esc(a.state)}…</h3><p class="muted">Correlating source, account, and target context. Recommendations will appear when all stages complete.</p><progress max="6" value="${a.stage}" aria-label="Investigation progress"></progress></div></section>`}</div></div>`;
}
function analysisContent(a) {
  const x = a.analysis;
  return `<section class="panel">${panelHead('Rule-based assessment', 'ai', badge('Local analysis', 'neutral'))}<div class="panel-body"><p class="analysis-summary">${esc(x.summary)}</p><div class="analysis-facts"><div><small>CLASSIFICATION</small>${badge(x.classification)}</div><div><small>SEVERITY</small>${badge(a.severity)}</div><div><small>CONFIDENCE</small><b class="cyan-text">${x.confidence}%</b></div><div><small>RISK SCORE</small><b>${x.risk}<span class="muted"> / 100</span></b></div></div><p class="fine-print spaced no-margin">${esc(x.caveat)}</p></div></section><div class="narrative"><p class="eyebrow">ATTACK NARRATIVE · EVIDENCE TO EXPLANATION</p><p>${esc(x.narrative)}</p></div><section class="panel">${panelHead('Context retrieval', 'layers', badge('4 local sources', 'neutral'))}<div class="panel-body"><div class="context-grid">${x.context.map(c => `<div class="context-source"><strong>${esc(c.name)}</strong><p>${esc(c.detail)}</p><small>${esc(c.type)}</small></div>`).join('')}</div><div class="context-equation">CONTEXT + ALERT EVENTS → LOCAL ANALYSIS ADAPTER</div></div></section><section class="panel">${panelHead('MITRE ATT&CK mapping', 'network')}<div class="panel-body">${x.mapping.length ? `<div class="attack-chain">${x.mapping.map((t, i) => `${i ? icon('arrow') : ''}<a class="technique-chip" href="${techniqueUrl(t.id)}" target="_blank" rel="noreferrer"><b>${t.id} · ${esc(t.tactic)}</b><span>${esc(t.name)}</span></a>`).join('')}</div>${x.mapping.map(t => `<p class="analysis-summary spaced no-margin"><b>${t.id} evidence:</b> ${esc(t.evidence)}</p>`).join('')}` : '<p class="muted no-margin">No ATT&CK technique asserted for this local policy match.</p>'}</div></section><section class="panel">${panelHead('Recommended response', 'shield', badge(a.decision ? a.state : x.classification === 'False positive' ? 'Suppressed' : 'Awaiting human approval', 'neutral'))}<div class="panel-body"><ol class="recommendations">${x.recommendations.map(r => `<li>${esc(r)}</li>`).join('')}</ol>${a.decision ? `<div class="section-note">${icon('check')}Analyst decision recorded: ${a.state}. ${a.decision === 'approve' ? `${a.sourceIp} is blocked in this simulation.` : 'The source was not blocked by this decision.'}</div>` : x.classification === 'False positive' ? '<div class="section-note">Matched approved maintenance context. Suppressed from the active queue; evidence retained.</div>' : `<div class="response-actions"><button class="button primary" data-decision="approve" data-id="${a.id}">${icon('check')}Approve response</button><button class="button ghost" data-decision="reject" data-id="${a.id}">Reject</button><button class="button ghost" data-decision="escalate" data-id="${a.id}">Escalate</button><span class="human-note">Review the advice. Human decides.</span></div>`}</div></section>`;
}
export function lab(s) {
  const running = s.running && scenarios.find(x => x.id === s.running.id);
  return `${heading('lab')}<div class="section-note">${icon('shield')}Controlled simulation only. Scenarios generate internal records; they never scan devices or send attack traffic.</div><div class="page-subheading"><h2>Scenario console</h2><div class="heading-actions"><button class="button ghost" data-action="traffic">${icon(s.normalTraffic ? 'pause' : 'play')}${s.normalTraffic ? 'Pause normal traffic' : 'Start normal traffic'}</button><button class="button ghost" data-action="reset">${icon('refresh')}Reset environment</button></div></div>${running ? `<div class="run-console">${icon('activity')}<div><p class="eyebrow">SCENARIO RUNNING</p><h3>${running.name}</h3><p>${s.running.index} / ${running.count} events generated · 1 event / second</p></div><progress class="right" value="${s.running.index}" max="${running.count}" aria-label="Scenario progress"></progress><button class="button ghost" data-action="stop">Stop scenario</button></div>` : ''}<div class="scenario-library">${scenarios.map((s,i)=>`<article class="scenario-entry ${s.id==='compromise'?'signature':''}"><span class="scenario-number">${String(i+1).padStart(2,'0')}</span><div class="scenario-copy"><p class="eyebrow">${s.category}${s.id==='compromise'?' · Recommended first':''}</p><h3>${s.name}</h3><p>${s.description}</p><small>${s.detection}</small></div><dl class="scenario-facts"><dt>Source → target</dt><dd>${s.source} → ${s.target}</dd><dt>Duration</dt><dd>${s.duration} seconds · ${s.count} events</dd></dl><div class="scenario-run">${badge(s.risk)}<button class="button ${s.id==='compromise'?'primary':'ghost'}" data-scenario="${s.id}" ${running?'disabled':''}>${icon('play')}Start simulation</button></div></article>`).join('')}</div><p class="fine-print spaced">Reset permanently removes lab events, alerts, decisions, blocklist entries, and portal registrations. The five baseline simulated devices remain.</p>`;
}
export const devices = inventory;
export function deviceDetail(d, s) {
  const related = s.events.filter(e => e.sourceIp === d.ip || e.destinationIp === d.ip);
  return `<p class="mono cyan-text">${d.ip}</p><dl class="definition">${Object.entries({ 'Hostname': d.hostname, 'Role': d.role, 'Operating system': d.os, 'Connection': d.status, 'Trust': d.trust, 'First seen': new Date(d.firstSeen).toLocaleString(), 'Last seen': new Date(d.lastSeen).toLocaleString(), 'Events generated': number(d.events), 'Alerts': s.alerts.filter(a => a.sourceIp === d.ip).length, 'Risk score': `${d.risk} / 100`, 'Traffic volume': `${(d.bytes / 1000000).toFixed(2)} MB (recorded)`, 'MAC address': d.mac, 'Peer address': d.peerIp || 'Synthetic — no physical peer' }).map(([k, v]) => `<dt>${k}</dt><dd>${esc(v)}</dd>`).join('')}</dl><hr class="divider"><h3>Recent communication</h3>${related.length ? `<div class="table-wrap"><table><thead><tr><th>TIME</th><th>PEER</th><th>EVENT</th></tr></thead><tbody>${related.slice(0, 7).map(e => `<tr><td class="mono muted">${time(e.timestamp)}</td><td class="mono">${e.sourceIp === d.ip ? e.destinationIp : e.sourceIp}</td><td>${esc(e.label)}</td></tr>`).join('')}</tbody></table></div>` : '<p class="muted">No communication recorded yet.</p>'}`;
}
export function registerForm() {
  return `<form id="register-form"><div class="form-grid"><label>Hostname<input name="hostname" required pattern="[A-Za-z0-9_-]{2,40}" placeholder="LAB-LAPTOP-02" maxlength="40"></label><label>Private logical IP<input name="ip" required placeholder="192.168.1.30"></label><label>Device role<select name="role">${roles.map(r => `<option>${r}</option>`).join('')}</select></label><label>Operating system<select name="os"><option>Windows</option><option>Android</option><option>iOS</option><option>Linux</option><option>macOS</option></select></label></div><div class="section-note spaced">${icon('info')}New devices start untrusted. This creates a simulated inventory record, without discovering or contacting a device.</div><p id="register-error" class="form-error" role="alert"></p><div class="modal-actions"><button type="button" class="button ghost" data-action="close-modal">Cancel</button><button type="submit" class="button primary">Register device</button></div></form>`;
}
export function mitre(s) {
  return `${heading('mitre')}<div class="section-note">${icon('layers')}Curated local ATT&CK dataset · mappings describe possible behavior, not proof of an attack. Select a technique for the primary MITRE reference.</div><div class="page-subheading"><h2>Detection coverage</h2><span class="muted">${Object.keys(techniques).length} techniques modeled</span></div><div class="technique-grid">${Object.entries(techniques).map(([id, t]) => { const list = s.alerts.filter(a => a.techniques.includes(id)); return `<article class="panel technique-card"><div class="eyebrow">${t.tactic}</div><span class="mono">${id}</span><h3>${t.name}</h3><p>${t.description}</p><div class="section-note">${list.length} correlated alerts · ${list.reduce((n, a) => n + a.eventIds.length, 0)} evidence links</div><p class="spaced"><b>Evidence:</b> ${t.evidence}</p><div class="queue-bottom"><a href="${techniqueUrl(id)}" target="_blank" rel="noreferrer" class="text-button">MITRE reference ↗</a>${list[0] ? `<button class="text-button" data-alert="${list[0].id}">Investigate ${icon('arrow')}</button>` : '<span class="muted">No current detections</span>'}</div></article>`; }).join('')}</div>`;
}
export function response(s) {
  const pending = s.alerts.filter(a => a.analysis && a.analysis.classification !== 'False positive' && !a.decision);
  return `${heading('response')}<div class="section-note">${icon('shield')}HUMAN-IN-THE-LOOP · Approval changes only this lab’s simulated blocklist and session behavior. No operating system firewall is modified.</div><div class="split spaced"><section class="panel">${panelHead('Awaiting analyst decision', 'alert', `<span class="count">${pending.length}</span>`)}<div class="panel-body">${pending.length ? pending.map(compactAlert).join('') : empty('No pending recommendations', 'Completed investigations will appear here for analyst review.')}</div></section><section class="panel">${panelHead('Simulated firewall blocklist', 'shield', badge(`${s.blocked.length} restricted`, 'neutral'))}<div class="panel-body">${s.blocked.length ? s.blocked.map(ip => `<div class="response-record">${icon('lock')}<div><h3 class="mono">${ip}</h3><p>${esc(s.devices.find(d => d.ip === ip)?.hostname)} · Subsequent requests blocked</p></div>${badge('Blocked', 'critical')}</div>`).join('') : empty('No source restrictions', 'An approved response adds the selected source to this simulation’s blocklist.')}</div></section></div><section class="panel spaced">${panelHead('Analyst decision log', 'layers', '<span class="muted">Shared lab history</span>')}${s.responses.length ? s.responses.map(r => `<div class="response-record">${icon(r.decision === 'approve' ? 'check' : r.decision === 'reject' ? 'close' : 'arrow')}<div><h3>${r.id} · ${r.alertId} · ${esc(r.analyst)}</h3><p>${esc(r.action)}</p><small class="mono muted">${r.sourceIp}</small></div>${badge(r.decision, 'neutral')}<time>${time(r.timestamp)}</time></div>`).join('') : empty('No decisions recorded', 'Approve, reject, or escalate an investigation to create an audit entry.')}</section>`;
}
export function analytics(s) {
  const m = metrics(s), count = pred => s.events.filter(pred).length, reviewed = m.reviewed;
  const cards = [
    ['Events over time', lineChart(s.rate.map(r => r.count)), 'Events / second · actual sampled rate'],
    ['Alerts by severity', bars(['critical', 'high', 'medium', 'low'].map((name, i) => ({ name: name.toUpperCase(), value: s.alerts.filter(a => a.severity === name).length, color: ['red', 'amber', 'cyan', 'green'][i] }))), 'All retained alerts, including decided alerts'],
    ['Authentication activity', bars(['LOGIN_ATTEMPT', 'LOGIN_SUCCESS', 'LOGIN_FAILED'].map(name => ({ name: name.replace('LOGIN_', ''), value: count(e => e.eventType === name), color: name === 'LOGIN_FAILED' ? 'amber' : 'cyan' }))), 'Recorded authentication events'],
    ['Normal vs. suspicious', bars([{ name: 'Normal · low risk', value: count(e => e.risk === 'low'), color: 'green' }, { name: 'Suspicious · elevated risk', value: count(e => e.risk !== 'low'), color: 'amber' }, { name: 'Blocked requests', value: count(e => e.action === 'Blocked'), color: 'red' }]), 'Risk is a rule signal; blocked requests also count as low risk'],
    ['Analysis classifications', bars([{ name: 'True positive', value: reviewed.filter(a => a.analysis.classification === 'True positive').length, color: 'amber' }, { name: 'Needs review', value: reviewed.filter(a => a.analysis.classification === 'Needs review').length, color: 'cyan' }, { name: 'False positive', value: m.suppressed, color: 'green' }, { name: 'Pending analysis', value: s.alerts.length - reviewed.length }]), 'Heuristic classifications, subject to human review'],
    ['False positives filtered', `<div class="analytics-number">${m.suppressed}</div>${bars([{ name: 'Suppressed / reviewed alerts', value: m.suppressed, color: 'green' }], reviewed.length || 1)}`, `${reviewed.length ? (m.suppressed / reviewed.length * 100).toFixed(1) : '0'}% of reviewed alerts · not a measured reduction benchmark`],
    ['Top source devices', bars([...s.devices].sort((a, b) => b.events - a.events).slice(0, 5).map(d => ({ name: d.hostname, value: d.events }))), 'Cumulative events per registered device'],
    ['Attack techniques', bars(Object.keys(techniques).map(id => ({ name: id, value: s.alerts.filter(a => a.techniques.includes(id)).length })).filter(x => x.value)), 'Alert mappings may contain more than one technique'],
    ['MTTR simulation', `<div class="analytics-number">${s.responses.filter(r => r.decision === 'approve').length ? (s.responses.filter(r => r.decision === 'approve').reduce((n, r) => n + r.seconds, 0) / s.responses.filter(r => r.decision === 'approve').length).toFixed(1) + '<small>s</small>' : '—'}</div>`, 'Mean alert-to-approval time. Seeded alerts include elapsed time since fixture creation; no production baseline.'],
    ['Rule confidence distribution', bars(['<70%', '70–79%', '80–89%', '90–100%'].map((name, i) => ({ name, value: reviewed.filter(a => i === 0 ? a.analysis.confidence < 70 : a.analysis.confidence >= 60 + i * 10 && a.analysis.confidence < (i === 3 ? 101 : 70 + i * 10)).length }))), 'Heuristic scores; not calibrated probabilities']
  ];
  return `${heading('analytics')}<div class="analytics-grid">${cards.map(([title, body, note]) => `<section class="panel">${panelHead(title, 'chart')}<div class="panel-body">${body}<p class="spaced no-margin">${note}</p></div></section>`).join('')}</div><div class="split spaced"><section class="panel">${panelHead('Target / research benchmark', 'layers', badge('Not achieved results', 'neutral'))}<div class="table-wrap"><table class="benchmark-table"><tbody>${[['F1 score target', '≥92%'], ['False positive reduction target', '60–75%'], ['MTTR improvement benchmark', '33–68%'], ['Analyst workload reduction benchmark', '≥39%'], ['Narrative generation target', '<3 seconds']].map(([k, v]) => `<tr><td>${k}</td><td class="mono cyan-text">${v}</td></tr>`).join('')}</tbody></table></div><p class="panel-body muted no-margin">User-supplied project targets. Research citations and a representative evaluation dataset are still required to validate these benchmarks.</p></section><section class="panel">${panelHead('Actual simulation result', 'activity', badge('Measured locally', 'low'))}<div class="table-wrap"><table><tbody>${[['Events generated', number(s.totalEvents)], ['Correct labeled alert classifications', `${m.correct} / ${m.labeled.length}`], ['False positives filtered', m.suppressed], ['Average analysis time', `${m.analysisTime}${m.reviewed.length ? ' seconds' : ''}`], ['Representative F1 score', 'Not evaluated'], ['Production workload / MTTR reduction', 'Not evaluated']].map(([k, v]) => `<tr><td>${k}</td><td class="mono">${v}</td></tr>`).join('')}</tbody></table></div><p class="panel-body muted no-margin">Correctness uses synthetic fixture labels only; physical portal events are unlabeled. Retained-event charts may cover fewer rows than the cumulative counter.</p></section></div>`;
}
export const architectureSteps = [
  ['Physical / simulated devices', 'Intentional activity', 'Employee interaction or scenario configuration', 'Structured application activity', 'Employee portal / scenario generator', 'employee01 opens the internal dashboard.'],
  ['Windows audit policy', 'Choose which events Windows records', 'Logon, process creation, account changes, and blocked packets', 'Security audit records', 'Windows auditpol', 'Enable the event categories you need to monitor.'],
  ['Windows collector', 'Read selected Security log records', 'Event IDs 4624, 4625, 4688, account changes, and 5152', 'Small event metadata batches', 'PowerShell Event Log API', 'The collector polls Windows Security every three seconds.'],
  ['Authenticated ingestion', 'Send records to the SOC app', 'Event metadata and private sensor token', 'Deduplicated Windows event records', 'POST /api/sensors/windows', 'The collector sends records over the local or hosted connection.'],
  ['Normalization', 'Use one consistent schema', 'Raw application fields', 'Normalized SOC event', 'SOCEngine.ingest()', 'sourceIp, destinationIp, eventType, status, risk.'],
  ['Event correlation', 'Link related behavior', '60-second source, target and account window', 'Related event set', 'JavaScript correlation rules', 'Six failures followed by successful authentication.'],
  ['Alert generation', 'Raise a rule-backed signal', 'Threshold match and supporting event IDs', 'Alert with severity and evidence', 'detectRules()', 'Potential credential compromise · HIGH.'],
  ['LLM contextualization', 'Prepare an analysis request', 'Alert, related events and device context', 'Structured adapter input', 'Server-side Gemini / OpenAI / Ollama evidence adapter', 'Source is untrusted; target is the auth server.'],
  ['RAG / threat intelligence', 'Retrieve reference context', 'Alert rule and technique IDs', 'Four local context sources', 'Local policy and ATT&CK data', 'T1110, auth policy, event history and behavioral indicator.'],
  ['False positive classification', 'Assess the signal in context', 'Correlated evidence and policy references', 'Classification and heuristic confidence', 'analyzeAlert()', 'Approved maintenance + trusted account → false positive.'],
  ['Attack narrative', 'Explain the observed sequence', 'Evidence and contextual assessment', 'Human-readable possible attack narrative', 'Deterministic narrative adapter', 'Failures followed by success suggest possible compromise.'],
  ['MITRE ATT&CK mapping', 'Describe possible techniques', 'Observed behavioral pattern', 'Technique IDs and evidence links', 'Curated local ATT&CK dataset', 'T1110 → T1078; verify with analyst.'],
  ['Response recommendation', 'Propose next investigative actions', 'Classification, severity and context', 'Analyst-reviewable response plan', 'Local response templates', 'Review activity, invalidate simulated sessions, restrict source.'],
  ['Human approval', 'Keep decisions with the analyst', 'Completed assessment and recommendations', 'Approve, reject or escalate decision', 'SOC investigation workspace', 'Analyst explicitly approves containment.'],
  ['Simulated response', 'Apply simulated lab containment', 'Approved response and source device', 'Blocked lab source and decision record', 'SOCEngine.decide()', 'Future lab requests from the source display BLOCKED.']
];
export function architecture() {
  return `${heading('architecture')}<section class="windows-setup"><div><p class="eyebrow">WINDOWS SECURITY LOG COLLECTOR</p><h2>Collect logs from this PC</h2><p>The PowerShell collector reads selected Windows Security events and posts their metadata to the SOC app. It does not install an agent server or capture packet contents.</p></div><ol><li><b>1</b><span>Start the app with <code>npm run start:lan</code> and run PowerShell as Administrator.</span></li><li><b>2</b><span>Run <code>npm run setup:windows</code> to enable the required audit categories and start the collector.</span></li><li><b>3</b><span>Open Event stream and look for records marked <code>Windows Event Log</code>. Keep the elevated PowerShell window open while collecting.</span></li></ol><div class="section-note">${icon('info')}The collector reads selected Security events only. It does not detect every attack; ping activity appears only when Windows firewall auditing records blocked packets.</div></section><div class="section-note">${icon('info')}Select a stage to inspect how Windows evidence reaches analyst review. Keep <code>SENSOR_INGEST_TOKEN</code> private, especially when hosting the app publicly.</div><div class="architecture-flow spaced">${architectureSteps.map(([title, purpose], i) => `<button class="architecture-block" data-architecture="${i}"><span class="eyebrow">STAGE ${String(i + 1).padStart(2, '0')} ${icon('arrow')}</span><b>${title}</b><small>${purpose}</small></button>`).join('')}</div><section class="panel spaced">${panelHead('What runs where', 'network')}<div class="panel-body split"><div><h3>Windows computer</h3><p class="analysis-summary">Windows Security logs, audit policy, and the PowerShell collector.</p></div><div><h3>SOC app</h3><p class="analysis-summary">Event ingestion, deduplication, local correlation rules, alert queue, analyst review, and controlled scenarios.</p></div></div></section>`;
}
export function about() {
  return `${heading('about')}<section class="panel about-intro"><p class="eyebrow cyan-text">FINAL-YEAR ENGINEERING PROJECT</p><h2>From event records<br>to analyst decisions.</h2><p>A controlled SOC demonstration that receives selected Windows Security logs and lab activity, groups related evidence, and presents it for human review.</p><div class="about-grid"><div><h3>The question</h3><p>How can an analyst move from security alerts to a clear decision?</p></div><div><h3>What this project does</h3><p>Collects selected Windows log metadata, correlates event patterns, and explains why activity needs review.</p></div><div><h3>Human oversight</h3><p>An analyst reviews, approves, rejects, or escalates each recommendation. Containment only affects the project’s simulated blocklist.</p></div><div><h3>Coverage</h3><p>Coverage depends on Windows audit policy and enabled event channels. No monitoring tool can promise detection of every attack; alerts need human review.</p></div></div><hr class="divider"><div class="attack-chain">${['COLLECT', 'CORRELATE', 'ANALYZE', 'EXPLAIN', 'RESPOND'].map((t, i) => `${i ? icon('arrow') : ''}${badge(t, 'neutral')}`).join('')}</div><div class="section-note spaced">${icon('flask')}Demo accounts: employee01 / employee123 · admin / secureadmin. Use only these fictional credentials.</div><div class="heading-actions spaced"><a class="button primary" href="#lab">Open Scenarios ${icon('arrow')}</a><a class="button ghost" href="/employee.html" target="_blank">Open employee portal ↗</a></div></section>`;
}
export function networkPage(s) { return `${heading('network')}<section class="panel">${panelHead('Private lab network', 'network', badge('Logical topology', 'neutral'))}${network(s, true)}</section><div class="section-note spaced">${icon('info')}Select a node to inspect it. Active devices appear first. Moving markers show recent application or Windows sensor records; green means normal access, amber means suspicious activity, and red stops at simulated policy. All devices remain in the inventory below.</div><div class="panel spaced">${panelHead('Connected assets', 'devices', goto('devices', 'Manage devices'))}<div class="table-wrap"><table><thead><tr><th>HOSTNAME</th><th>LOGICAL IP</th><th>ROLE</th><th>TRUST</th><th>RISK</th><th>STATUS</th><th></th></tr></thead><tbody>${s.devices.map(d => `<tr><td>${esc(d.hostname)}</td><td class="mono">${d.ip}</td><td>${esc(d.role)}</td><td>${esc(d.trust)}</td><td>${d.risk}/100</td><td>${badge(d.status)}</td><td><button class="text-button" data-device="${d.ip}">Inspect ${icon('arrow')}</button></td></tr>`).join('')}</tbody></table></div></div>`; }
export const views = { command, traffic, alerts, investigations, lab, devices, mitre, response, analytics, architecture, about, network: networkPage };
