import { esc, icon, badge, time, number } from './utils.js';
import { network } from './network.js';
import { metrics } from './charts.js';
import { connectionPanel } from './connect.js';

const sections = [
  ['Workspace', [['command', 'Overview', 'grid'], ['traffic', 'Event stream', 'activity'], ['alerts', 'Alert queue', 'alert'], ['investigations', 'Investigations', 'search']]],
  ['Sources', [['devices', 'Devices', 'devices'], ['lab', 'Scenarios', 'flask'], ['architecture', 'Windows logs', 'network']]]
];
const titles = { command: 'Security overview', network: 'Lab network', traffic: 'Event stream', alerts: 'Alert queue', investigations: 'Investigation workspace', response: 'Incident response', devices: 'Devices & connection', lab: 'Simulation scenarios', analytics: 'Analytics', mitre: 'MITRE ATT&CK', architecture: 'Windows log collection', about: 'About this project' };
const descriptions = { command: 'Events, sources, and decisions from your local lab.', network: 'See which lab devices exchanged activity.', traffic: 'Inspect incoming Windows events and controlled lab records.', alerts: 'Review detections with their supporting event records.', investigations: 'Inspect the event sequence and decide what happens next.', response: 'Review analyst decisions and simulated containment.', devices: 'Connect a device or inspect observed lab sources.', lab: 'Generate controlled activity and follow its events.', analytics: 'Review the activity and results collected in this session.', mitre: 'View the techniques modeled by this lab.', architecture: 'Configure the Windows Security log collector for this computer.', about: 'SOC Analyst · Final-year engineering project' };

export function headingNew(route) {
  if (route === 'command') return '';
  return `<div class="page-heading"><div><h1>${titles[route]}</h1><p>${descriptions[route]}</p></div><div class="heading-actions">${['devices','network'].includes(route) ? `<button class="button primary" data-action="connect">${icon('devices')}Connect a device</button>` : ''}</div></div>`;
}
export function shellNew(route) {
  return `<div class="brand"><a href="#command" class="brand-lockup" aria-label="SOC Analyst overview"><span class="brand-symbol">${icon('activity')}</span><span>SOC <em>/</em> ANALYST<small>Security operations lab</small></span></a></div><nav class="navigation" aria-label="Main navigation">${sections.map(([name, items]) => `<div class="nav-group"><p class="nav-section-label">${name}</p>${items.map(([id, label, glyph]) => `<a class="nav-item ${route === id ? 'active' : ''}" href="#${id}" title="${label}" ${route === id ? 'aria-current="page"' : ''}>${icon(glyph)}<span>${label}</span></a>`).join('')}</div>`).join('')}</nav><div class="sidebar-lab"><i class="dot green"></i><span>Private lab<small>Simulated response</small></span></div>`;
}
export function utilityNew(s, ui) {
  const status = ui.connected ? 'Collector connected' : 'Reconnecting…';
  return `<div class="utility-location">Workspace <span>/</span> <b>Private lab</b></div><div class="utility-right"><span class="connection-label"><i class="dot ${ui.connected ? 'green' : 'amber'}"></i>${status}</span><span class="utility-time mono">${time(Date.now())}</span><button class="shortcut" data-action="palette" aria-label="Open command palette">${icon('search')}<kbd>Ctrl K</kbd></button><button class="icon-button" data-action="presentation" aria-label="Toggle presentation mode" title="Presentation mode">${icon('expand')}</button><button class="icon-button" data-action="notifications" aria-label="Notifications">${icon('bell')}</button><button class="avatar-button" data-action="profile" aria-label="Analyst profile">AM</button></div>`;
}
function reviewRow(a) {
  return `<button class="review-row" data-alert="${a.id}"><span class="review-marker ${a.severity}"></span><span class="review-copy"><span class="review-meta">${a.id}<span>${a.severity}</span></span><strong>${esc(a.title)}</strong><small>${esc(a.sourceIp)} <span>·</span> ${a.analysis ? 'Ready for review' : esc(a.state)}</small></span>${icon('chevron')}</button>`;
}
export function overview(s, ui) {
  const m = metrics(s), devices = s.devices.filter(d => !d.synthetic && !d.sensorManaged && d.status === 'Connected');
  const windows = s.events.filter(e => e.origin === 'Windows Event Log'), portal = s.events.filter(e => ['Lab portal','Portal simulation'].includes(e.origin)), simulation = s.events.filter(e => e.origin === 'Synthetic');
  const windowsFresh = windows.length && Date.now() - Date.parse(windows[0].timestamp) < 20000;
  const active = [...m.active].sort((a,b) => ({critical:0,high:1,medium:2,low:3}[a.severity] ?? 4)-({critical:0,high:1,medium:2,low:3}[b.severity] ?? 4)).slice(0,4);
  const latest = s.events.slice(0,8);
  const eventRows = latest.map(e => {
    const meta = e.origin === 'Windows Event Log' ? 'Windows Event Log · event ' + (e.windowsEvent?.eventId || '—') + ' · ' + (e.windowsEvent?.computer || e.sourceDevice || 'endpoint') : e.origin;
    return '<article class="signal-row"><time class="signal-time">' + time(e.timestamp) + '</time><span class="signal-mark ' + e.risk + '"><i></i></span><div class="signal-copy"><div class="signal-title">' + esc(e.label) + '<span class="signal-source">' + esc(meta) + '</span></div><div class="signal-detail"><span>' + esc(e.sourceIp) + ' <b>→</b> ' + esc(e.destinationIp) + '</span><span>' + esc(e.protocol) + (e.port ? ' / ' + e.port : '') + '</span><span>' + esc(e.user) + '</span></div></div><span class="signal-result ' + e.action.toLowerCase() + '">' + esc(e.action) + '</span></article>';
  }).join('');
  const sources = [
    {name:'Windows Event Log',count:windows.length,note:windows.length?'records received':'collector not connected',glyph:'activity',state:windowsFresh?'receiving':windows.length?'quiet':'waiting',href:'#architecture',action:'Set up collector',code:!windows.length},
    {name:'Employee portal',count:portal.length,note:devices.length?'live device sessions':'no devices connected',glyph:'devices',state:devices.length?'receiving':'ready',href:'#devices',action:'Connect a device'},
    {name:'Scenario lab',count:simulation.length,note:'controlled demo records',glyph:'flask',state:'ready',href:'#lab',action:'Choose a scenario'}
  ];
  const sourceCards = sources.map(x => '<article class="source-card"><div class="source-card-top"><span class="source-glyph ' + x.glyph + '">' + icon(x.glyph) + '</span><span class="source-state ' + x.state + '"><i></i>' + (x.state==='receiving'?'Receiving':x.state==='waiting'?'Waiting':'Ready') + '</span></div><h3>' + x.name + '</h3><div class="source-count">' + number(x.count) + ' <small>' + x.note + '</small></div>' + (x.code?'<div class="collector-command"><span>Windows setup</span><code>npm run setup:windows</code></div>':'') + '<a class="source-action" href="' + x.href + '">' + x.action + ' <span>→</span></a></article>').join('');
  const queueCards = active.length ? active.map(a => '<button class="queue-item" data-alert="' + a.id + '"><span class="queue-severity ' + a.severity + '">' + a.severity + '</span><strong>' + esc(a.title) + '</strong><small>' + esc(a.sourceIp) + ' → ' + esc(a.destinationIp) + ' · ' + a.eventIds.length + ' records</small><span class="queue-rule">' + esc(a.initialRule) + '</span></button>').join('') : '<div class="queue-clear"><span>✓</span><h3>Nothing needs review</h3><p>Rule matches will appear here with the records that triggered them.</p></div>';
  return '<div class="overview-title"><div><p class="eyebrow">SOC / LOCAL OPERATIONS</p><h1>Activity overview</h1><p>Incoming records, recent detections, and the next analyst decision.</p></div><div class="overview-actions"><button class="button ghost" data-action="demo">Walkthrough</button><a class="button primary" href="#traffic">Open event stream ' + icon('arrow') + '</a></div></div>' +
    '<div class="overview-stats">' + [['Records in session',number(s.totalEvents),'All sources'],['Needs review',number(m.active.length),number(m.active.filter(a => ['critical','high'].includes(a.severity)).length) + ' high priority'],['Connected devices',number(devices.length),'Employee portal sessions'],['Windows log records',number(windows.length),'Security events received']].map((x,i) => '<article class="overview-stat stat-' + (i+1) + '"><span>' + x[0] + '</span><strong>' + x[1] + '</strong><small>' + x[2] + '</small></article>').join('') + '</div>' +
    '<section class="source-board"><div class="section-heading"><div><span class="eyebrow">COLLECTION</span><h2>Where records come from</h2></div><a class="text-button" href="#architecture">Collection setup ' + icon('arrow') + '</a></div><div class="source-cards">' + sourceCards + '</div></section>' +
    '<div class="overview-columns"><section class="signal-board"><div class="section-heading"><div><span class="eyebrow">LATEST RECORDS</span><h2>Recent Windows logs & activity</h2><p>Security event, endpoint, account, and event context.</p></div><a class="text-button" href="#traffic">All records ' + icon('arrow') + '</a></div>' +
    (latest.length ? '<div class="signal-list">' + eventRows + '</div>' : '<div class="signal-empty"><div class="signal-empty-icon">' + icon('activity') + '</div><h3>No records received yet</h3><p>Start the Windows log collector, connect a portal device, or run a lab scenario. New records will appear here.</p><div class="heading-actions"><a class="button primary" href="#architecture">Windows setup</a><a class="button ghost" href="#lab">Run a scenario</a></div></div>') + '</section>' +
    '<aside class="review-board"><div class="section-heading"><div><span class="eyebrow">ANALYST QUEUE</span><h2>Decisions waiting</h2><p>Open an alert to inspect its evidence.</p></div><a class="queue-total" href="#alerts">' + number(m.active.length) + '</a></div><div class="queue-list">' + queueCards + '</div>' + (active.length ? '<a class="queue-link" href="#alerts">Open alert queue ' + icon('arrow') + '</a>' : '') + '</aside></div>' +
    '<section class="flow-board"><div class="section-heading"><div><span class="eyebrow">THE WORKFLOW</span><h2>From Windows event to analyst review</h2></div></div><div class="flow-steps"><div><b>01</b><strong>Collect</strong><small>PowerShell reads selected Security log events</small></div><span>→</span><div><b>02</b><strong>Send</strong><small>Collector posts records to this app</small></div><span>→</span><div><b>03</b><strong>Correlate</strong><small>Local rules group suspicious activity</small></div><span>→</span><div><b>04</b><strong>Review</strong><small>Analyst checks event evidence</small></div></div></section>' +
    '<div class="overview-foot"><span>Academic lab · response actions affect only the project’s simulated blocklist.</span><a href="#lab">Run a controlled scenario ' + icon('arrow') + '</a></div>';
}export function inventory(s, ui) {
  const physical = s.devices.filter(d=>!d.synthetic&&!d.sensorManaged), observed=s.devices.filter(d=>d.sensorManaged), synthetic=s.devices.filter(d=>d.synthetic);
  const rows = list => list.map(d=>`<tr><td><button class="device-name" data-device="${d.ip}">${icon(d.role.includes('Server')?'server':d.os==='Android'||d.os==='iOS'?'phone':'devices')}<span>${esc(d.hostname)}<small>${esc(d.os)} · ${esc(d.role)}</small></span></button></td><td class="mono">${esc(d.peerIp || d.ip)}<small class="table-secondary">${d.synthetic?'Simulated address':`Lab ID: ${d.ip}`}</small></td><td>${badge(d.status,d.status==='Offline'?'neutral':undefined)}${d.simulation?`<small class="table-secondary">${esc(d.simulation.name)}<br>${esc(d.simulation.state)} · ${d.simulation.index} / ${d.simulation.total} events</small>`:''}</td><td class="mono">${number(d.events)}</td><td class="mono muted">${time(d.lastSeen)}</td><td><button class="text-button" data-device="${d.ip}">Details ${icon('chevron')}</button></td></tr>`).join('');
  const table = list => `<div class="table-wrap"><table><thead><tr><th>Device</th><th>${list[0]?.synthetic?'Lab address':'Network address'}</th><th>Status</th><th>Events</th><th>Last seen</th><th></th></tr></thead><tbody>${rows(list)}</tbody></table></div>`;
  return `${headingNew('devices')}<section class="connection-workspace">${connectionPanel(ui.config,physical)}</section><section class="panel spaced"><div class="panel-header"><div><h2>Live device sessions <span class="count">${physical.length}</span></h2><p>Browsers intentionally connected through the employee portal</p></div></div>${physical.length?table(physical):'<div class="waiting-devices"><span class="waiting-icon">'+icon('devices')+'</span><div><h3>Ready when your devices are</h3><p>Scan the code above on your phone, register it, and it will appear here automatically.</p></div></div>'}</section>${observed.length?`<section class="panel spaced"><div class="panel-header"><div><h2>Sensor-observed sources <span class="count">${observed.length}</span></h2><p>Private lab addresses seen in authenticated sensor events</p></div></div>${table(observed)}</section>`:''}<section class="panel spaced"><div class="panel-header"><div><h2>Simulated lab assets <span class="count">${synthetic.length}</span></h2><p>Built-in devices used by the scenario engine</p></div><button class="button ghost small" data-action="register">Add simulated device</button></div>${table(synthetic)}</section>`;
}
