import test from 'node:test';
import assert from 'node:assert/strict';
import { createLabServer } from '../server.js';
import { createHostedAuth } from '../lib/hosted-auth.js';

const password='Test-only-analyst-password',joinCode='test-only-invitation-0123456789',publicUrl='https://soc.example.test';
test('hosted mode requires credentials, protects the console and supports invited devices',async t=>{
  const {server,engine}=createLabServer({hosted:true,password,joinCode,publicUrl});
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  t.after(()=>new Promise(resolve=>{server.closeAllConnections();server.close(resolve);}));
  const base=`http://127.0.0.1:${server.address().port}`;
  const post=(path,data={},cookie='',token='')=>fetch(base+path,{method:'POST',redirect:'manual',headers:{Origin:publicUrl,'Content-Type':'application/json',...(cookie?{Cookie:cookie}:{}),...(token?{'X-Device-Token':token}:{})},body:JSON.stringify(data)});
  assert.equal(engine.state.events.length,0);
  assert.equal((await fetch(base+'/',{redirect:'manual'})).headers.get('location'),'/analyst-login.html');
  for(const path of ['/api/state','/api/stream','/api/join-qr.svg']) assert.equal((await fetch(base+path)).status,401,path);
  assert.equal((await post('/api/action',{name:'reset'})).status,401,'Loopback must not bypass hosted authentication');
  const anonymous=await(await fetch(base+'/api/config')).json();assert.equal(anonymous.control,false);assert.deepEqual(anonymous.portalUrls,[]);
  assert.equal((await post('/api/auth/login',{password:'incorrect'})).status,401);
  const login=await post('/api/auth/login',{password});assert.equal(login.status,200);
  const setCookie=login.headers.get('set-cookie');assert.match(setCookie,/HttpOnly/);assert.match(setCookie,/Secure/);assert.match(setCookie,/SameSite=Strict/);
  const cookie=setCookie.split(';')[0];
  const config=await(await fetch(base+'/api/config',{headers:{Cookie:cookie}})).json();
  assert.equal(config.control,true);assert.equal(config.portalUrls[0],`${publicUrl}/employee.html?join=${joinCode}`);
  assert.equal((await fetch(base+'/api/state',{headers:{Cookie:cookie}})).status,200);
  assert.equal((await fetch(base+'/api/join-qr.svg',{headers:{Cookie:cookie}})).status,200);
  const details={hostname:'HOSTED-PHONE',role:'Test Device',os:'Android'};
  assert.equal((await post('/api/register',details)).status,403);
  const registered=await(await post('/api/register',{...details,joinCode})).json();assert.ok(registered.token);
  assert.equal(registered.device.peerIp,'Hosted session');
  assert.equal((await post('/api/portal',{action:'demo-sequence',scenario:'api'},'',registered.token)).status,202);
  assert.equal((await post('/api/action',{name:'reset'},'',registered.token)).status,401,'Participant token must not grant analyst privileges');
  assert.equal((await fetch(base+'/api/action',{method:'POST',headers:{Cookie:cookie,Origin:'https://attacker.test','Content-Type':'application/json'},body:'{"name":"reset"}'})).status,403);
  assert.equal((await post('/api/shutdown',{},cookie)).status,403);
  for(const path of ['/lib/hosted-auth.js','/render.yaml','/server.js','/.env']) assert.equal((await fetch(base+path)).status,404,path);
  assert.equal((await post('/api/action',{name:'reset'},cookie)).status,200);
  assert.equal((await post('/api/portal',{action:'heartbeat'},'',registered.token)).status,401);
  const stream=await fetch(base+'/api/stream',{headers:{Cookie:cookie}});const reader=stream.body.getReader();await reader.read();
  assert.equal((await post('/api/auth/logout',{},cookie)).status,303);
  assert.equal((await reader.read()).done,true,'Sign-out terminates the existing event stream');
  assert.equal((await fetch(base+'/api/state',{headers:{Cookie:cookie}})).status,401);
});
test('hosted authentication fails closed and rate limits guessing',()=>{
  assert.throws(()=>createHostedAuth({password:'short',joinCode,publicUrl}),/12/);
  assert.throws(()=>createHostedAuth({password,joinCode:'short',publicUrl}),/24/);
  assert.throws(()=>createHostedAuth({password,joinCode,publicUrl:'http://public.example'}),/HTTPS/);
  const auth=createHostedAuth({password,joinCode,publicUrl});
  for(let i=0;i<10;i++)assert.equal(auth.login('wrong','peer').status,401);
  assert.equal(auth.login(password,'peer').status,429);
  assert.equal(auth.validInvitation('wrong'),false);
});
